contact/urls.py
from django.urls import path
app_name = 'contact'

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('export/xlsx', views.export, name='export_xlsx'),
    path('add/', views.add, name='add'),
    path('edit/<int:contact_id>', views.edit, name='edit'),
    path('del/<int:contact_id>', views.delete, name='delete'),
]

iniproject/urls.py
u"""iniproject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path, re_path
# from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page=settings.LOGIN_URL), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('', include('contact.urls', namespace='contact')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

# if settings.DEBUG:
#   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models
from . import utils

# Create your models here.
class Contact(models.Model):
    # Create field
    name = models.CharField(max_length=50, unique=True)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField(blank=True)
    gender = models.CharField(max_length=6)
    profile_picture = models.ImageField(upload_to=utils.pfp_handle, blank=True)
    
    def save(self, *args, **kwargs):
      # Check data from id
      try:
        this = Contact.objects.get(id=self.id)
        # If the image data not same with the image, delete image (pfp changed)
        if this.profile_picture != self.profile_picture:
          this.profile_picture.delete(save=False)
      except:
        pass
      super().save(*args, **kwargs)
    
    def __str__(self):
        return f"{self.name}"

contact/forms.py
from django import forms
from django.core.exceptions import ValidationError
from . import models

class ContactForm(forms.ModelForm):
  # For Gender radio-button
  GENDER_CHOICES = (
    ('male', 'Male'),
    ('female', 'Female'),
    ('askme', 'Ask Me'),
  )
  
  # Create radio-button
  gender = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect())
  
  # Generate forms from model
  class Meta:
    model = models.Contact
    fields = '__all__'
  
  # Check if inserted is numbers
  def clean_phone_number(self):
    # Get phone number
    try:
      phone_number = self.cleaned_data.get('phone_number')
      int(phone_number)
      return phone_number
    # Return error if not numbers
    except ValueError:
      raise ValidationError('Can only contain numbers.')
  
  # Check if there is a same name
  # def clean_name(self):
  #   # Get name
  #   name = self.cleaned_data.get('name')
  #   name_value = name.lower()
  #   # Check name that same from form that inputed by user
  #   data = models.Contact.objects.filter(name__iexact=name_value)
  #   # If data edited, let name same (exclude the name so there isn't have any data)
  #   if self.instance:
  #     data = data.exclude(pk=self.instance.pk)
  #   else:
  #     data = data
  #   # If data exist, show an error, else continue the logic
  #   if data.exists() == True:
  #     raise ValidationError(f'{name} is already exists.')
  #   else:
  #     return name

iniproject/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class SignUpForm(UserCreationForm):
  class Meta:
    model = User
    fields = ('username', 'email', 'password1', 'password2')
  
  def clean_email(self):
    email_value = self.cleaned_data.get('email')
    data = User.objects.filter(email__iexact=email_value).exists()
    if data == True:
      raise ValidationError('A user with that email already exists.')
    else:
      return email_value
  
  def save(self):
    user = super(UserCreationForm, self).save()
    user.email = self.cleaned_data.get('email')
    user.set_password(self.cleaned_data.get('password1'))
    user.save()
    return user

contact/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib import messages
from . import models, forms, resource, utils

# Create your views here.

@login_required(login_url=settings.LOGIN_URL)
def index(request):
  if request.GET.get('search'):
    keyword = request.GET['search']
    contacts = models.Contact.objects.filter(name__contains=keyword)
  else:
    contacts = models.Contact.objects.all()
  page = request.GET.get("page", 1)
  contacts = Paginator(contacts, 5).get_page(page)
  ctx = {
    'pagetitle': 'Home',
    'h1_data': 'Contact List',
    'contacts': contacts,
    'search': request.GET.get('search', ''),
  }
  
  return render(request, 'contact/index.html', ctx)

@login_required(login_url=settings.LOGIN_URL)
def add(request):
  error = None
  if request.POST:
    form_data = forms.ContactForm(request.POST, request.FILES)
    if form_data.is_valid():
      form_data.save()
      messages.success(request, f'Successfully added { request.POST["name"] }!')
      return redirect('contact:index')
    else:
      error = form_data.errors
  form = forms.ContactForm()
  ctx = {
      'pagetitle': 'Add Contact',
      'h1_data': 'Add Contact',
      'form': form,
      'error': error,
  }
  return render(request, 'contact/add.html', ctx)
      
@login_required(login_url=settings.LOGIN_URL)
def edit(request, contact_id):
  error = None
  if request.POST:
    contact = models.Contact.objects.get(id=contact_id)
    form_data = forms.ContactForm(request.POST, request.FILES, instance=contact)
    if form_data.is_valid():
      form_data.save()
      messages.success(request, f'Successfully edited { request.POST["name"] }!')
      return redirect('contact:index')
    else:
      error = form_data.errors
  contact = models.Contact.objects.get(id=contact_id)
  form = forms.ContactForm(instance=contact)
  ctx = {
      'pagetitle': f'Edit { contact.name }',
      'h1_data': f'Edit { contact.name }',
      'contact': contact,
      'form': form,
      'error': error,
  }
  return render(request, 'contact/edit.html', ctx)

@login_required(login_url=settings.LOGIN_URL)
def delete(request, contact_id):
  contact = models.Contact.objects.get(id=contact_id)
  # contact.profile_picture.delete()
  contact.delete() # will automatically delete with the photo
  
  return redirect('contact:index')
    

@login_required(login_url=settings.LOGIN_URL)
def export(request):
  contacts = resource.ContactResource()
  dataset = contacts.export()
  response = HttpResponse(dataset.xlsx, content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
  response['Content-Disposition'] = 'attachment; filename=mycontact.xlsx'
  return response

iniproject/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib import messages
from . import forms

@login_required(login_url=settings.LOGIN_URL)
def signup(request):
  error = None
  if request.POST:
    form = forms.SignUpForm(request.POST)
    if form.is_valid():
      form.save()
      messages.success(request, f"Successfully created { request.POST['username'] }!")
      return redirect('contact:index')
    else:
      messages.error(request, "Something went wrong...")
      error = form.errors
  form = forms.SignUpForm()
  ctx = {
      'pagetitle': 'Sign Up',
      'h1_data': 'Sign Up',
      'error': error,
      'form': form,
  }
  return render(request, 'registration/signup.html', ctx)

contact/templates/contact/add.html
{% extends 'base.html' %}

{% block content %}
  
  <div class="row d-flex justify-content-center">
    <div class="col-md-6">
      
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <table>
          {{ form.as_table }}
        </table>
        <button ="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>
  
{% endblock %}

contact/templates/contact/edit.html
{% extends 'base.html' %}

{% block content %}
  
  <div class="row d-flex justify-content-center">
    <div class="col-md-6">
      
  <form action="" method="post"  enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
      
    </table>
    <button ="submit" class="btn btn-primary">Submit</button>
    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete-{{ contact.id }}">Delete</button>
    <a class="btn btn-secondary" href="{{request.META.HTTP_REFERER}}">Back</a>
  </form>
  </div></div>

<div class="modal fade" id="delete-{{ contact.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Delete</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure want to delete {{ contact.name }}?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
        <a href="{% url 'contact:delete' contact.id %}" class="btn btn-danger">Yes</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

contact/templates/contact/index.html
{% extends 'base.html' %}

{% block content %}
  
  <div class="row d-flex justify-content-center">
    
    <div class="col-md-6">
      
      <div class="d-flex justify-content-evenly">
        <a href="{% url 'contact:add' %}" class="btn btn-primary">Add Contact</a>
        <a href="{% url 'contact:export_xlsx' %}" class="btn btn-success">Export as .xlsx</a>
      </div>

      <form action="" method="get" class="mt-3 mb-3 input-group justify-content-center">
        <input type="text" name="search">
        <button class="btn btn-secondary" type="submit">Search</button>
      </form>
    </div>
  </div>
  
  <div class="container">
    {% if "?search" in request.get_full_path %}
      <a href="{% url 'contact:index' %}">&laquo;Go back</a>
    {% endif %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Pfp</th>
        <th scope="col">Name</th>
        <th scope="col">Phone Number</th>
      </tr>
    </thead>
    <tbody>
      {% for contact in contacts %}
      <tr>
        <td>
          {% if contact.profile_picture %}
          <img src="{{ contact.profile_picture.url }}" alt="{{ contact.name}}" width="90">
          {% endif %}
        </td>
        <td><a href="{% url 'contact:edit' contact.id %}">{{ contact.name }}</a></td>
        <td>{{ contact.phone_number }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  </div>

<div class="container d-flex justify-content-center">
<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if contacts.has_previous %}
    <li class="page-item">
      <a class="page-link" href="{% if search %}?search={{search}}&{% else %}?{% endif %}page={{contacts.previous_page_number}}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% endif %}

    {% for numpage in contacts.paginator.page_range %}
      {% if numpage == contacts.number %}
        <li class="page-item active" aria-current="page">
          <a class="page-link" href="#">{{ numpage }}</a>
        </li>
      {% else %}
        <li class="page-item" aria-current="page">
          <a class="page-link" href="{% if search %}?search={{search}}&{% else %}?{% endif %}page={{numpage}}">{{ numpage }}</a>
        </li>
      {% endif %}
    {% endfor %}

    {% if contacts.has_next %}
    <li class="page-item">
      <a class="page-link" href="{% if search %}?search={{search}}&{% else %}?{% endif %}page={{contacts.next_page_number}}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
</div>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{{ pagetitle }}</title>
  <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" />
</head>
<body>
  
  {% if user.is_authenticated %}
  
    <p class="text-end mt-2 me-3">
      Hi, <b>{{ user }}</b> | <a href="{% url 'signup' %}">Sign Up</a> | <a href="{% url 'logout' %}">Logout</a>
    </p>
  
  {% endif %}
    <h1 class="text-center">{{ h1_data }}</h1>
    
    {% for message in messages %}
      {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-danger">ERROR: {{ message }}</div>
      {% else %}
        <div class="alert alert-success">{{ message }}</div>
      {% endif %}
    {% endfor %}
    
    {% if error %}

      <div>{{ error }}</div>

    {% endif %}
    
  {% block content %}{% endblock %}

<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>